In [1]:
import numpy as np

In [2]:
#creating the arrays
mylist = [1,3,4]

In [4]:
type(mylist)

list

In [5]:
myarray = np.array(mylist)

In [6]:
type(myarray)

numpy.ndarray

In [11]:
a = np.arange(0,10,2)

In [12]:
a

array([0, 2, 4, 6, 8])

In [17]:
np.ones(shape=(5,5)) #rows colums

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.random.seed(101)
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [28]:
arr2 = np.random.randint(0,100,10)
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [29]:
arr.max()

95

In [30]:
arr.argmax()

0

In [31]:
arr.min()

9

In [32]:
arr.argmin()

7

In [33]:
arr.mean()

60.8

In [37]:
arr.reshape(5,2)

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [38]:
mat = np.arange(0,100).reshape(10,10)

In [39]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

mat[0,5]

In [41]:
mat[0,1]

1

In [42]:
mat[4,6]

46

In [44]:
mat[:,4]  # every single value for column 4

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [46]:
mat[:3,6:] = 0

In [49]:
newmat = mat.copy()

newmat[:3,4:] = 99

In [50]:
newmat[:3,4:] = 99


In [51]:
newmat

array([[ 0,  1,  2,  3, 99, 99, 99, 99, 99, 99],
       [10, 11, 12, 13, 99, 99, 99, 99, 99, 99],
       [20, 21, 22, 23, 99, 99, 99, 99, 99, 99],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])